### ISSUE TITLE
Check metal maps

### ISSUE THREAD

**Issue by sprunk** [Spring-Helper-Projects/Lua-Mex#4]
Should be tested on speedmetal (or other similar map) if it hasn't yet been.

**Comment by ScarylePoo** [comment]
Speedmetal works ok, but pure lua-mex config maps don't actually provide any metal to the metal extractors. 

https://i.imgur.com/mXfvQ5m.png

The tops don't spin and the tooltip + resourcebar report no actual income. I was looking for more than one indication  just to make sure. :-P

Edit: Lua-Mex is in BA proper now (Master).

Edit2: You can use Xiu Bi Crossing as examples. BA has a game specific config for the first version, the second version has a config mapside: http://springfiles.com/spring/spring-maps/xiu-bi-crossing

**Comment by sprunk** [comment]
>pure lua-mex config maps don't actually provide any metal to the metal extractors.

That's because BA uses engine mexes and not Lua mexes.

**Comment by ScarylePoo** [comment]
That explains a lot actually. I was wondering how it was supposed to work.

I'm guessing that lua mexes involves ripping apart https://github.com/ZeroK-RTS/Zero-K/blob/ca7f714f725cec5a9e743420b2f6e8010255de3f/LuaRules/Gadgets/unit_mex_overdrive.lua ?

Ideally with luamex, I would prefer to bypass engine mexing altogether. Render the balls inert, so to speak.

**Comment by ScarylePoo** [comment]
This has been resolved with the move to total lua mexing. Thank you @sprunk <3
